; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = ESP32_S3_SuperMini
default_envs = ESP32_S3_WROOM1_DevKitC_1_N16R8
;default_envs = LILYGO_T_DONGLE_S3 ; esp32-s3-r8  (16 Mb flash - NO PSRAM)
;default_envs = WAVESHARE_ESP32_S3_PICO         ;FLASH 16Mb PSRAM 2Mb - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2

[env]

[esp32]
platform_packages = 

[common]
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32.git#55.03.34 ; Arduino Release v3.3.4 based on ESP-IDF v5.5.1.251106
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.35 ; Arduino Release v3.3.5 based on ESP-IDF v5.5.1+

lib_deps = 
	adafruit/Adafruit ST7735 and ST7789 Library @^1.11.0
	Adafruit TinyUSB Library = https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#3.7.3
    ;;; lovyan03/LovyanGFX@^1.2.7
    ;LovyanGFX Library = https://github.com/lovyan03/LovyanGFX.git#develop
    LovyanGFX Library = https://github.com/lovyan03/LovyanGFX.git#2689b7c12e384558991d324e19bc67782f986551  ; ramo develop - 13 dic 2025
    adafruit/Adafruit SSD1306@^2.5.14

build_unflags = 
	-std=gnu++11
	-std=gnu11
    -Og

build_flags = 
	;-D DEBUG_OPENFIRE
    -D DONGLE
	-D USE_TINYUSB
    -D USE_LOVYAN_GFX
	-std=gnu++17
	-std=gnu17
    -O2
	
[display_ESP32_S3_WROOM1_DevKitC_1_N16R8]
build_unflags = 

build_flags = 
    -D USER_SETUP_LOADED        ;solo adafruit
    -D ST7735_DRIVER            ;solo adafruit
    -D SPI_HOST=VSPI_HOST       ;solo lgfx
    -D SPI_MODE=0               ;solo lgfx
    -D SPI_FREQUENCY=50000000
    -D TFT_MISO=-1
    -D TFT_MOSI=3
    -D TFT_SCLK=5
    -D TFT_CS=4 
    -D TFT_DC=2 
    -D TFT_RST=1 
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D TFT_OFFSET_X=0           ;solo lgfx
    -D TFT_OFFSET_Y=0           ;solo lgfx
    -D TFT_INVERT=1             ;solo lgfx
    -D TFT_RGB_ORDER=0
    -D LOAD_GLCD                ;solo adafruit
    -D LOAD_FONT2               ;solo adafruit
    -D LOAD_FONT4               ;solo adafruit
    -D LOAD_FONT6               ;solo adafruit
    -D LOAD_FONT7               ;solo adafruit
    -D LOAD_FONT8               ;solo adafruit
    -D LOAD_GFXFF               ;solo adafruit
    -D SMOOTH_FONT              ;solo adafruit
    -D ST7735_GREENTAB160x80    ;solo adafruit
    ;-D TFT_RGB_ORDER=TFT_BGR
	;-D TFT_RGB_ORDER=0

[display_ESP32_S3_SuperMini]
build_unflags = 

build_flags = 
    -D USER_SETUP_LOADED        ;solo adafruit
    -D ST7735_DRIVER            ;solo adafruit
    -D SPI_HOST=SPI2_HOST       ;solo lgfx
    -D SPI_MODE=0               ;solo lgfx
    -D SPI_FREQUENCY=80000000
    -D TFT_MISO=-1
    -D TFT_MOSI=39
    -D TFT_SCLK=40
    -D TFT_CS=36
    -D TFT_DC=37 
    -D TFT_RST=38 
    -D TFT_PIN_BL=35            ;solo lgfx
    -D TFT_PIN_BL_PWM_CHANNEL=-1 ;solo lgfx
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D TFT_OFFSET_X=26           ;solo lgfx
    -D TFT_OFFSET_Y=1           ;solo lgfx
    -D TFT_INVERT=1             ;solo lgfx
    -D TFT_RGB_ORDER=0
    -D LOAD_GLCD                ;solo adafruit
    -D LOAD_FONT2               ;solo adafruit
    -D LOAD_FONT4               ;solo adafruit
    -D LOAD_FONT6               ;solo adafruit
    -D LOAD_FONT7               ;solo adafruit
    -D LOAD_FONT8               ;solo adafruit
    -D LOAD_GFXFF               ;solo adafruit
    -D SMOOTH_FONT              ;solo adafruit
    -D ST7735_GREENTAB160x80    ;solo adafruit
    ;-D TFT_RGB_ORDER=TFT_BGR
	;-D TFT_RGB_ORDER=0

[display_LILYGO_T_DONGLE_S3]
build_unflags = 

build_flags = 
    -D USER_SETUP_LOADED        ;solo adafruit
    -D ST7735_DRIVER            ;solo adafruit
    -D SPI_HOST=SPI2_HOST       ;solo lgfx
    -D SPI_MODE=0               ;solo lgfx
    -D SPI_FREQUENCY=80000000
    -D TFT_MISO=-1
    -D TFT_MOSI=3
    -D TFT_SCLK=5
    -D TFT_CS=4 
    -D TFT_DC=2 
    -D TFT_RST=1 
    -D TFT_PIN_BL=38            ;solo lgfx
    -D TFT_PIN_BL_PWM_CHANNEL=-1 ;solo lgfx
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D TFT_OFFSET_X=26           ;solo lgfx
    -D TFT_OFFSET_Y=1           ;solo lgfx
    -D TFT_INVERT=1             ;solo lgfx
    -D TFT_RGB_ORDER=0
    -D LOAD_GLCD                ;solo adafruit
    -D LOAD_FONT2               ;solo adafruit
    -D LOAD_FONT4               ;solo adafruit
    -D LOAD_FONT6               ;solo adafruit
    -D LOAD_FONT7               ;solo adafruit
    -D LOAD_FONT8               ;solo adafruit
    -D LOAD_GFXFF               ;solo adafruit
    -D SMOOTH_FONT              ;solo adafruit
    -D ST7735_GREENTAB160x80    ;solo adafruit
    ;-D TFT_RGB_ORDER=TFT_BGR
	;-D TFT_RGB_ORDER=0

[display_WAVESHARE_ESP32_S3_PICO]
build_unflags = 

build_flags = 
    -D USER_SETUP_LOADED        ;solo adafruit
    -D ST7735_DRIVER            ;solo adafruit
    -D SPI_HOST=SPI2_HOST       ;solo lgfx
    -D SPI_MODE=0               ;solo lgfx
    -D SPI_FREQUENCY=80000000
    -D TFT_MISO=-1
    -D TFT_MOSI=39
    -D TFT_SCLK=40
    -D TFT_CS=36
    -D TFT_DC=37 
    -D TFT_RST=38 
    -D TFT_PIN_BL=35            ;solo lgfx
    -D TFT_PIN_BL_PWM_CHANNEL=-1 ;solo lgfx
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D TFT_OFFSET_X=26           ;solo lgfx
    -D TFT_OFFSET_Y=1           ;solo lgfx
    -D TFT_INVERT=1             ;solo lgfx
    -D TFT_RGB_ORDER=0
    -D LOAD_GLCD                ;solo adafruit
    -D LOAD_FONT2               ;solo adafruit
    -D LOAD_FONT4               ;solo adafruit
    -D LOAD_FONT6               ;solo adafruit
    -D LOAD_FONT7               ;solo adafruit
    -D LOAD_FONT8               ;solo adafruit
    -D LOAD_GFXFF               ;solo adafruit
    -D SMOOTH_FONT              ;solo adafruit
    -D ST7735_GREENTAB160x80    ;solo adafruit
    ;-D TFT_RGB_ORDER=TFT_BGR
	;-D TFT_RGB_ORDER=0


[env:LILYGO_T_DONGLE_S3]
platform = ${common.platform}
board = LILYGO-T-DONGLE-S3
;board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
	${common.build_unflags}
	${display_LILYGO_T_DONGLE_S3.build_unflags}
build_flags = 
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=84 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	;-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
	-D DEVICE_LILYGO_T_DONGLE_S3
	-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_LILYGO_T_DONGLE_S3.build_flags}
;board_build.partitions = huge_app.csv
;board_build.partitions = huge_app_OF_4MB.csv
board_build.partitions = default_OF_16MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
platform_packages = 
	${esp32.platform_packages}
lib_ldf_mode = chain
lib_compat_mode = strict

[env:ESP32_S3_WROOM1_DevKitC_1_N16R8]
platform = ${common.platform}
;board = esp32-s3-devkitc-1
board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
	${common.build_unflags}
	${display_ESP32_S3_WROOM1_DevKitC_1_N16R8.build_unflags}
build_flags = 
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N16R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=84 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	;-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	; -D USES_DISPLAY
	-D USES_OLED_DISPLAY
	-D OLED_SDA=18
	-D OLED_SCL=15  
	-D DUAL_CORE
	${common.build_flags}
	${display_ESP32_S3_WROOM1_DevKitC_1_N16R8.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = default_OF_16MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_PICO]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-PICO-N16R2
;board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
	${common.build_unflags}
	${display_WAVESHARE_ESP32_S3_PICO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_PICO
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=84 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	;-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_WAVESHARE_ESP32_S3_PICO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = default_OF_16MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
lib_ldf_mode = chain
lib_compat_mode = strict

[env:ESP32_S3_SuperMini]

platform = ${common.platform}
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600 ;115200
board_build.partitions = default.csv
lib_deps = 
	; Adafruit TinyUSB Library@^3.4.4
	; adafruit/Adafruit ST7735 and ST7789 Library @^1.10.4
	; adafruit/Adafruit SSD1306@^2.5.14
	; adafruit/Adafruit GFX Library@^1.11.9
	; adafruit/Adafruit BusIO@^1.15.0
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
	${common.build_unflags}
	${display_ESP32_S3_WROOM1_DevKitC_1_N16R8.build_unflags}
build_flags = 
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N16R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
;	-D USES_DISPLAY
	-D USES_OLED_DISPLAY
	-D USE_SSD1306_OLED
	; -D OLED_SDA=8
	; -D OLED_SCL=9
	-D OLED_SDA=13
	-D OLED_SCL=12
	-D OLED_I2C_ADDR=0x3C	
	;-D DUAL_CORE
	${common.build_flags}
;	${display_ESP32_S3_WROOM1_DevKitC_1_N16R8.build_flags}
platform_packages = ${esp32.platform_packages}
lib_ldf_mode = chain
lib_compat_mode = strict